service: gather-radio

frameworkVersion: ">=1.1.0 <=2.41.2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  changeStation:
    handler: handler.change_station
    events:
      - http:
          path: stream-url
          method: post
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: gather-radio